name: geo
channels:
  - conda-forge
dependencies:
  - python=3.12
  - numpy=2.3.*
  - pandas
  - pyarrow
  - numexpr
  - bottleneck
  - geopandas
  - rasterio
  - pyproj
  - shapely
  - fiona
  - gdal
  - jupyterlab
  - seaborn
  - matplotlib
  - statsmodels
  - scipy
  - scikit-learn
  - rtree
  - numba
  - spreg
  - esda
  - libpysal
  - splot
