name: geo
channels:
  - conda-forge
dependencies:
  - python=3.10
  - 'numpy<2'
  - pandas
  - pyarrow
  - numexpr
  - bottleneck
  - geopandas
  - rasterio
  - pyproj
  - shapely
  - fiona
  - gdal
  - jupyterlab
  - seaborn
  - matplotlib
  - statsmodels
  - scipy
  - scikit-learn
  - pysal
  - rtree
  - pip
  - pip:
    - spreg
